// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/katex/katex.d.ts
declare namespace katex {
  
	interface KatexOptions {
		displayMode?: boolean;
		breakOnUnsupportedCmds?: boolean;
		errorColor?: string;
	}

	class ParseError implements Error {
		constructor(message: string, lexer: any, position: number);
		name: string;
		message: string;
		position: number;
	}

	/**
	 * Renders a TeX expression into the specified DOM element
	 * @param tex A TeX expression
	 * @param element The DOM element to render into
	 * @param options KaTeX options
	 */
	function render(tex: string, element: HTMLElement, options?: KatexOptions): void;
	/**
	 * Renders a TeX expression into an HTML string
	 * @param tex A TeX expression
	 * @param options KaTeX options
	 */
	function renderToString(tex: string, options?: KatexOptions): string;

}
